```{r message=FALSE, warning=FALSE}
#plotting 
library(ggplot2)
library(gridExtra)
library(cowplot)
library(ggOceanMaps) #this package draws maps, and puts points on the maps
library (ggspatial)
library(ocedata)
library(oce) #this package draws maps, and puts points on the maps

#data handling
library(data.table)
library(dplyr)
library(magrittr)
library(reshape2)
library(stringr)
library(scales)
library(tidyr)
library(tidyverse)

setwd("C:/Users/ljabre/OneDrive - Mount Allison University/Desktop/work/science_projects/oceanmetaproteomesmap/")

```

some useful links to help with plotting 
```{r}
#https://www.benjaminbell.co.uk/2019/08/bathymetric-maps-in-r-getting-and.html

```

OPP
https://www.oceanproteinportal.org/about-datasets

2025-12-05 -- import the data
```{r}
alldata <- read.csv ("../oceanmetaproteomesmap/oceanmetaPs.csv")
```

2026-01-20 -- data quality control and metadata
```{r}


```


2025-12-05 Global Map
```{r}
basemap("DecimalDegree",  bathymetry = F, #bathy.style = "raster_continuous_grays",
        grid.col = "NA",
        glaciers = F) + 
        geom_spatial_point(data = subset(alldata, !grepl("sBrum", citation)),
 
                           aes(x = Lon_dd_W, y = Lat_dd_N, color = citation), 
                               size = 2,  alpha = 0.7) + 
  theme(
   # legend.position = "bottom", 
    legend.position = "none",
    legend.title = element_blank())


#Zoom in on certain areas 
basemap(limits = c(90, 100, -70, 70),  bathymetry = F, #bathy.style = "rcb",
      #  grid.col = "NA",
        glaciers = F) + 
        geom_spatial_point(data = alldata, 
                           aes(Lon_dd_W, y = Lat_dd_N, color = citation), 
                               size = 4,  alpha = 0.5) 
```


2026-01-20  Southern Ocean / Antarctica
```{r}
#antarctica
basemap(limits = -60,  bathymetry = T, 
        #grid.col = "NA",
        glaciers = F) + 
        geom_spatial_point(data = alldata, 
                           aes(x = Lon_dd_W, y = Lat_dd_N, color = citation), 
                              size = 4,  alpha = 0.5) 


basemap(limits = c(-90,120,-60,-40),  bathymetry = F, 
        #grid.col = "NA",
        glaciers = F) + 
        geom_spatial_point(data = alldata, 
                           aes(x = Lon_dd_W, y = Lat_dd_N, color = citation), 
                              size = 4,  alpha = 0.5) 
```


2026-01-20  Arctic
```{r}
basemap(limits = 30,  bathymetry = F, 
        glaciers = F) + 
        geom_spatial_point(data = alldata, 
                           aes(Lon_dd_W, y = Lat_dd_N, color = citation), 
                               size = 4,  alpha = 0.5) 




#playing around with different perspectives andplotting angles.
berring_straight <- data.frame(lon = c(170,-150,-150, 170 ), lat = c(40, 70, 70, 40))

basemap (berring_straight)


basemap(limits = c(-130, 30, 30, 70))

#berring strait
basemap(limits = c(-130, 30, 30, 70),  bathymetry = F, #bathy.style = "rcb",
      #  grid.col = "NA",
        glaciers = F) + 
        geom_spatial_point(data = alldata, 
                           aes(Lon_dd_W, y = Lat_dd_N, color = citation), 
                               size = 4,  alpha = 0.5) 
```




